Windows, Linux, MacOS でテストの挙動を変更できるコードを追加
sinnchan/jis_okinawa_site_generator pull request #1
Opened 2021-06-15 14:51 UTC by Issei0804-ie

2021-06-16 23:36 UTC, sinnchan commented
差分が思ったより強すぎたのでやっぱりpackage-lock.jsonはナシで。。
パッケージの更新が必要になったらそのときにコミットでいいかも。。

2021-06-16 23:41 UTC, sinnchan requested changes

2021-06-16 23:41 UTC, sinnchan commented on src/domain/usecase/Executor.test.ts
> +        console.log("os is windows")
**os is Linux**

2021-06-16 23:41 UTC, sinnchan commented on src/domain/usecase/Executor.test.ts
> +        console.log("os is windows")
**os is Darwin**

2021-06-17 13:28 UTC, Issei0804-ie commented on src/domain/usecase/Executor.test.ts
> +        console.log("os is windows")
mac では...?

2021-06-17 13:29 UTC, Issei0804-ie commented on src/domain/usecase/Executor.test.ts
> +        console.log("os is windows")
> Darwin（ダーウィン）は、Appleが開発するUnix系のPOSIX準拠オペレーティングシステム (OS) である。(中略)DarwinはmacOSやiOS、さらにはwatchOSとtvOSの基礎となる部分でもある。

Darwin の方が良さそう

2021-06-17 13:35 UTC, sinnchan commented
LGTM

2021-06-17 13:35 UTC, merged